services:
    prometheus:
        image: prom/prometheus
        container_name: prometheus
        command:
            - "--config.file=/etc/prometheus/prometheus.yml"
        ports:
            - 9090:9090
        restart: unless-stopped
        volumes:
            - ./prometheus:/etc/prometheus
            - prom_data:/prometheus

    grafana:
        image: grafana/grafana
        container_name: grafana
        ports:
            - 31000:31000
        restart: unless-stopped
        environment:
            - GF_SERVER_HTTP_PORT=${GF_SERVER_HTTP_PORT}
            - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
            - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
        volumes:
            - ./grafana:/etc/grafana/provisioning/datasources

volumes:
    prom_data:
