services:

    grafana:
        image: grafana/grafana
        container_name: grafana
        ports:
            - 3000:3000
        restart: unless-stopped
        environment:
            - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
            - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
        volumes:
            - ./grafana:/etc/grafana/provisioning/datasources
            - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
            - ./grafana/dashboards:/var/lib/grafana/dashboards

    prometheus:
        image: prom/prometheus
        container_name: prometheus
        command:
            - --config.file=/etc/prometheus/prometheus.yml
        ports:
            - 9090:9090
        restart: unless-stopped
        volumes:
            - ./prometheus:/etc/prometheus
            - prom_data:/prometheus
        depends_on: # ? Update depends_on per each exporter using
            - mongodb_exporter
            - redis_exporter
            - elasticsearch_exporter
            - mysqld_exporter

    mongodb_exporter:
        image: bitnami/mongodb-exporter:latest
        container_name: mongodb_exporter
        ports:
            - 9216
        command:
            - --mongodb.uri=${MONGODB_URI}
            - --mongodb.direct-connect=${MONGODB_DIRECT_CONNECT}
            - --collect-all=true
        restart: unless-stopped

    redis_exporter:
        image: bitnami/redis-exporter:latest
        container_name: redis_exporter
        ports:
            - 9121
        command:
            - --redis.addr=${REDIS_URI}
            - --redis.user=${REDIS_USERNAME}
            - --redis.password=${REDIS_PASSWORD}
        restart: unless-stopped
        extra_hosts:  # ? Enable this when using localhost
            - host.docker.internal:host-gateway

    elasticsearch_exporter:
        image: bitnami/elasticsearch-exporter:latest
        container_name: elasticsearch_exporter
        ports:
            - 9114
        command:
            - --es.uri=${ELASTICSEARCH_URI}
            - --es.all
            - --es.indices
            - --es.indices_settings
            - --es.indices_mappings
        restart: unless-stopped

    mysqld_exporter:
        image: bitnami/mysqld-exporter:latest
        container_name: mysqld_exporter
        ports:
            - 9104
        command:
            - --mysqld.username=${MYSQL_USERNAME}:${MYSQL_PASSWORD}
            - --mysqld.address=${MYSQL_HOST}
        restart: unless-stopped
        extra_hosts:  # ? Enable this when using localhost
            - host.docker.internal:host-gateway

volumes:
    prom_data:
