# my global config
global:
  scrape_interval: 60s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 60s # Evaluate rules every 15 seconds. The default is every 1 minute.
  scrape_timeout: 30s # Is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - 'first_rules.yml'
  # - 'second_rules.yml'

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  # - job_name: mongodb-metrics
  #   scrape_interval: 60s
  #   scrape_timeout: 30s
  #   # scheme: https
  #   metrics_path: "/metrics"
  #   basic_auth:
  #     username: <>
  #     password: <>
  #   http_sd_configs:
  #     - url: <>
  #       refresh_interval: 60s
  #       basic_auth:
  #         username: <>
  #         password: <>

  - job_name: mongodb-exporter
    scrape_interval: 60s
    scrape_timeout: 30s
    # scheme: https
    metrics_path: "/metrics"
    static_configs:
      - targets: ["localhost:9216"]


  # - job_name: elasticsearch-exporter
  #   scrape_interval: 60s
  #   scrape_timeout: 30s
  #   # scheme: https
  #   metrics_path: "/metrics"
  #   static_configs:
  #     - targets: ["localhost:9114"]
  #       labels:
  #         service: elasticsearch
  #   basic_auth:
  #     username: <>
  #     password: <>
  #   relabel_configs:
  #     - source_labels: [__address__]
  #       regex: '(.*)\:9108'
  #       target_label: "instance"
  #       replacement: "$1"
  #     - source_labels: [__address__]
  #       regex: '.*\.(.*)\.lan.*'
  #       target_label: "environment"
  #       replacement: "$1"

  # - job_name: mysql-exporter
  #   scrape_interval: 60s
  #   scrape_timeout: 30s
  #   # scheme: https
  #   static_configs:
  #     - targets: ["localhost:9104"]
  #       labels:
  #         alias: <dbname>

  # - job_name: redis-exporter
  #   scrape_interval: 60s
  #   scrape_timeout: 30s
  #   # scheme: https
  #   static_configs:
  #     - targets: ["localhost:9121"]

  # - job_name: logging-service
  #   scrape_interval: 60s
  #   scrape_timeout: 30s
  #   # scheme: https
  #   metrics_path: "/api/v3/logging/ping"
  #   static_configs:
  #     - targets: ["localhost:3001"]

  # - job_name: neon-postgres-operations
  #   scrape_interval: 60s
  #   scrape_timeout: 30s
  #   # scheme: https
  #   metrics_path: "/api/v2/projects/<projectid>/operations"
  #   static_configs:
  #     - targets: ["https://console.neon.tech"]
