global:
  scrape_interval: 15s
  scrape_timeout: 10s

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  # MONGODB
  - job_name: mongodb_exporter
    static_configs:
      - targets:
          - mongodb_exporter:9216

  # REDIS
  ## config for the multiple Redis targets that the exporter will scrape
  # - job_name: redis_exporter_targets
  #   static_configs:
  #     - targets:
  #         - redis://first-redis-host:6379
  #         - redis://second-redis-host:6379
  #         - redis://second-redis-host:6380
  #   metrics_path: /scrape
  #   relabel_configs:
  #     - source_labels: [__address__]
  #       target_label: __param_target
  #     - source_labels: [__param_target]
  #       target_label: instance
  #     - target_label: __address__
  #       replacement: <<REDIS-EXPORTER-HOSTNAME>>:9121
  ## config for scraping the exporter itself
  - job_name: redis_exporter
    static_configs:
      - targets:
          - redis_exporter:9121


  # MYSQL
  ## config for the multiple Mysql targets that the exporter will scrape
  # - job_name: mysql_exporter_targets # To get metrics about the mysql exporter’s targets
  #   params:
  #     # Not required. Will match value to child in config file. Default value is `client`.
  #     auth_module: [client]
  #   static_configs:
  #     - targets:
  #         - server1:3306
  #         - server2:3306
  #   relabel_configs:
  #     - source_labels: [__address__]
  #       target_label: __param_target
  #     - source_labels: [__param_target]
  #       target_label: instance
  #     - target_label: __address__
  #       replacement: <<MYSQL-EXPORTER-HOSTNAME>>:9104
  ## config for scraping the exporter itself
  # - job_name: mysql_exporter
  #   static_configs:
  #     - targets:
  #         - mysql_exporter:9104

  # ELASTICSEARCH
  - job_name: elasticsearch_exporter
    static_configs:
      - targets:
          - elasticsearch_exporter:9114
