global:
  scrape_interval: 15s
  scrape_timeout: 10s

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  # MONGODB
  - job_name: mongodb_exporter
    static_configs:
      - targets:
          - mongodb_exporter:9216

  # REDIS
  - job_name: redis_exporter
    static_configs:
      - targets:
          - redis_exporter:9121


  # MYSQL
  - job_name: mysqld_exporter
    static_configs:
      - targets:
          - mysqld_exporter:9104

  # ELASTICSEARCH
  - job_name: elasticsearch_exporter
    static_configs:
      - targets:
          - elasticsearch_exporter:9114

  # KAFKA
  - job_name: kafka_exporter
    static_configs:
      - targets:
          - kafka_exporter:9308
